---
authors:
  - Ansible Network Community (ansible-network)
license_file: LICENSE
name: junos
namespace: juniper
readme: README.rst
repository: https://github.com/ansible-network/ansible_collections.juniper.junos
version: 0.0.1
